# frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: app-demo
spec:
  replicas: 2
  selector:
    matchLabels: {app: web}
  template:
    metadata:
      labels: {app: web}
    spec:
      # ▼▼▼ [修正] Podレベルのセキュリティ設定を追加 ▼▼▼
      # これにより、このPodで実行される全コンテナが非rootユーザーで実行されるようになります。
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      # ▲▲▲ 修正 ▲▲▲
      containers:
        - name: nginx
          image: nginx:1.27
          ports: [{containerPort: 80}]
          # ▼▼▼ [修正] コンテナレベルのセキュリティ設定を追加 ▼▼▼
          # restrictedポリシーの要件を明示的に満たします。
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          # ▲▲▲ 修正 ▲▲▲
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: conf
          configMap:
            name: nginx-conf
