# mysql/deployment.yaml  ★フル定義
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: app-demo
spec:
  replicas: 2
  selector:
    matchLabels: {app: web}
  template:
    metadata:
      labels: {app: web}
    spec:
      # ▼▼▼ 追加 ▼▼▼
      securityContext:
        runAsUser: 101       # nginxユーザーのUID
        runAsGroup: 101      # nginxグループのGID
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      # ▲▲▲ 追加 ▲▲▲
      containers:
        - name: nginx
          image: nginx:1.27
          ports: [{containerPort: 80}]
          # ▼▼▼ 追加 ▼▼▼
          securityContext:
            allowPrivilegeEscalation: false
            # runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          # ▲▲▲ 追加 ▲▲▲
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: conf
          configMap:
            name: nginx-conf
