# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: app-demo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpw
  MYSQL_USER: appuser
  MYSQL_PASSWORD: appsecret
  MYSQL_DATABASE: appdb
