apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app-demo
spec:
  replicas: 2
  selector:
    matchLabels: {app: api}
  template:
    metadata:
      labels: {app: api}
    spec:
      serviceAccountName: api-sa
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: api
        image: ghcr.io/example/go-api:latest # ←ビルドしたものに置換
        ports: [{containerPort: 8080}]
        env:
          - name: DB_HOST   # CoreDNS で `mysql.app-demo.svc.cluster.local`
            value: mysql
          - name: DB_USER
            valueFrom: {secretKeyRef: {name: mysql-secret, key: MYSQL_USER}}
          - name: DB_PASSWORD
            valueFrom: {secretKeyRef: {name: mysql-secret, key: MYSQL_PASSWORD}}
          - name: DB_NAME
            valueFrom: {secretKeyRef: {name: mysql-secret, key: MYSQL_DATABASE}}
        resources:
          requests: {cpu: 200m, memory: 256Mi}
          limits:   {cpu: 500m, memory: 512Mi}
        readinessProbe:
          httpGet: {path: /healthz, port: 8080}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: {path: /healthz, port: 8080}
          initialDelaySeconds: 15
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
