# mysql/deployment.yaml  ★フル定義
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: app-demo
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # ★ Pod レベルの seccomp
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 999
      containers:
        - name: mysql               # ← ここに必ず "- "
          image: mysql:8.4
          args: ["--default-authentication-plugin=mysql_native_password"]
          envFrom:
            - secretRef:
                name: mysql-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # ★ Container レベルの securityContext
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes: []   # ← volumeClaimTemplates を使用するので空配列で OK
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
