# mysql/deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: app-demo
spec:
  serviceName: mysql
  selector:
    matchLabels: {app: mysql}
  template:
    metadata:
      labels: {app: mysql}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-pvc # 作成したPVCの名前を指定
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mysql
        image: mysql:8.4
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: {secretKeyRef: {name: mysql-secret, key: MYSQL_ROOT_PASSWORD}}
          - name: MYSQL_DATABASE
            valueFrom: {secretKeyRef: {name: mysql-secret, key: MYSQL_DATABASE}}
          - name: MYSQL_USER
            valueFrom: {secretKeyRef: {name: mysql-secret, key: MYSQL_USER}}
          - name: MYSQL_PASSWORD
            valueFrom: {secretKeyRef: {name: mysql-secret, key: MYSQL_PASSWORD}}
        ports:
          - containerPort: 3306
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "127.0.0.1", "--password=$(MYSQL_ROOT_PASSWORD)"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysql", "-h", "127.0.0.1", "-p$(MYSQL_ROOT_PASSWORD)", "-e", "SELECT 1"]
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: data # ここで指定するnameは上のvolumesで定義したnameと一致させる
            mountPath: /var/lib/mysql
